baseURL = "https://mkordik.github.io/Notion-Hugo/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "DoIt"
[[menu.main]]
  name = "About" 
  identifier = "https://mkordik.github.io/Notion-Hugo/about/"
  weight = 1
