baseURL = "https://mkordik.github.io/Notion-Hugo/"
languageCode = "en-us"
title = "Micah Kordik"
theme = "congo"
[[menu.main]]
  name = "About" 
  url = "https://mkordik.github.io/Notion-Hugo/about"
  weight = 1
