baseURL = "https://mkordik.github.io/Notion-Hugo/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "DoIt"
[[menu.main]]
  name = "About" 
  url = "https://mkordik.github.io/Notion-Huge/about"
  weight = 1
